### ISSUE TITLE
Unable to start service com.huawei.hms.rn.push.remote.HmsPushMessageService

### ISSUE THREAD

**Issue by jeffy2007** [HMS-Core/hms-react-native-plugin#10]
Device: Huawei Mate 10 Pro
Android version: 10
Plugin version:  "@hmscore/react-native-hms-push": "^5.0.2-300"

When attempt to receive data message from server, I received this in the log:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trandllstudio.jcpstaging, PID: 18443
    java.lang.RuntimeException: Unable to start service com.huawei.hms.rn.push.remote.HmsPushMessageService@686d26a with Intent { act=com.huawei.push.action.MESSAGING_EVENT pkg=com.trandllstudio.jcpstaging (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4683)
        at android.app.ActivityThread.access$2900(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at com.huawei.hms.rn.push.logger.HMSLogger.setupEventMap(HMSLogger.java:292)
        at com.huawei.hms.rn.push.logger.HMSLogger.<init>(HMSLogger.java:78)
        at com.huawei.hms.rn.push.logger.HMSLogger.getInstance(HMSLogger.java:95)
        at com.huawei.hms.rn.push.remote.HmsPushMessageService.onMessageReceived(HmsPushMessageService.java:35)
        at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:185)
        at com.huawei.hms.push.HmsMessageService.onStartCommand(HmsMessageService.java:131)
        at com.huawei.hms.rn.push.remote.HmsPushMessageService.onStartCommand(HmsPushMessageService.java:90)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4663)
        at android.app.ActivityThread.access$2900(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by aktug** [comment]
Hi @jeffreycl 
This issue has been located and it will be fixed in the next version 🍻

**Comment by Zeroxys** [comment]
Hello @aktug this issue is solved in 5.0.2-301? because still have the same log
