### ISSUE TITLE
App crashas in Android while opening

### ISSUE THREAD

**Issue by Krish143git** [HMS-Core/hms-react-native-plugin#120]
hi guys, i am also facing the same issue app is not opening in android,But it is working on hms core apk presented device ,but not working in google service device.And also when i uninstall hms-push pkg it is opening in google service phones and when i install it is not opening in google service phones 

this is the logcat i am getting in android studio when opening

Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at com.huawei.hms.rn.push.logger.HMSLogger.getInstance(HMSLogger.java:100)
        at com.huawei.hms.rn.push.remote.HmsPushMessageService.onTokenError(HmsPushMessageService.java:107)
        at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:34)
        at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:29)
        at com.huawei.hms.push.HmsMessageService.handleIntentMessage(HmsMessageService.java:7)
        at com.huawei.hms.push.HmsMessageService$a.handleMessage(HmsMessageService.java:7)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by ozcanozgur** [comment]
Hi @Krish143git thank you for your interest in our Huawei Push React Native Plugin,

We have fixed the problem. The new version will be released on the next month.

Thank you.

**Comment by Krish143git** [comment]
ok thank you
