### ISSUE TITLE
App crash after launch

### ISSUE THREAD

**Issue by bulkinav** [HMS-Core/hms-react-native-plugin#140]
**Description**
From time to time, the application may crash with an error:

```
E/AndroidRuntime: FATAL EXCEPTION: pool-37-thread-4
    Process: com.ipspirates.ort, PID: 14800
    java.security.InvalidParameterException: url is null
        at com.huawei.agconnect.credential.obs.i.a(Unknown Source:48)
        at com.huawei.agconnect.credential.obs.i.a(Unknown Source:11)
        at com.huawei.agconnect.common.api.Backend.call(Unknown Source:4)
        at com.huawei.agconnect.credential.obs.t.a(Unknown Source:62)
        at com.huawei.agconnect.credential.obs.t.a(Unknown Source:0)
        at com.huawei.agconnect.credential.obs.t$1.run(Unknown Source:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

I think this occurs if your API server is down or does not respond. But this shouldn't throw a fatal exception anyway.

**Environment**
 - Platform: React-Native
 - Kit: Analytics and Push kits
 - Kit Version: 5.3.1-300
 - OS Version: reproduced on any Android version (checked on Android 11 and Android 8)
 - Your Location/Region: Russia, St. Petersburg

**build.gradle:**

```
...
implementation project(':react-native-hms-push')
implementation project(':react-native-hms-analytics')
...
```

**Comment by SerdarCanDev** [comment]
Hi @bulkinav , seems like your issue is related to  outdated `agconnect-services.json` file and enabling services. Please enable the services and download the file again for integration processes. You may also check this issue on [StackOverflow](https://stackoverflow.com/questions/62771127/huawei-push-and-sdk-statistics-issues) or [Official Huawei Documentations](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrating-rn-analytics-0000001059112334).
