### ISSUE TITLE
Crash on InterstitialAd.loadAd 

### ISSUE THREAD

**Issue by marf** [HMS-Core/hms-react-native-plugin#86]
**Description**
Hello, from our firebase console we see lots of crashes with this stack trace:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at com.huawei.hms.ads.w.Code(w.java:20)
       at com.huawei.hms.ads.w.Code(w.java:12)
       at com.huawei.hms.ads.InterstitialAd.loadAd(InterstitialAd.java:2)
       at com.huawei.hms.rn.ads.HMSAdsInterstitialAdModule.lambda$loadAd$0(HMSAdsInterstitialAdModule.java:209)
       at com.huawei.hms.rn.ads.HMSAdsInterstitialAdModule.lambda$loadAd$0$HMSAdsInterstitialAdModule(HMSAdsInterstitialAdModule.java)
       at com.huawei.hms.rn.ads.-$$Lambda$HMSAdsInterstitialAdModule$5OKlWN00oKt90NUqstcphOat7vE.run(-.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

In our App we display Huawei Interstitials ads.

To add more info:

in Firebase it shows that this crash happens when 99% of time when devices are in the background.
I think there is a bug loading interstitial ads while the app is in the background.

Any ideas on how to fix it? I tried to check the loadAd method but it is a black-box.

Thank you,
Marco

**Comment by alperentahta** [comment]
@marf I was unable to recreate the error case. Can you share more information?

**Comment by marf** [comment]
> @marf I was unable to recreate the error case. Can you share more information?

Hello, unfortunately, we do not have lots of info about this crash. In our crash report, we see that it happens 99% of the time in the background while we are loading a new ad.

**Comment by marf** [comment]
@alperentahta Can you give some ideas on what may cause this problem? This is by far our largest crash at the moment and seems to happen in the background only.

Thank you,
Marco

**Comment by alperentahta** [comment]
@marf I can't recreate the error. The information you have given is very insufficient. I would like to Help you but I need more information.

**Comment by marf** [comment]
> @marf I can't recreate the error. The information you have given is very insufficient. I would like to Help you but I need more information.

Hello, we have only this information, unfortunately.
